### ISSUE TITLE
References are not sorted alphabetically

### ISSUE THREAD

**Issue by rasvaan** [vtex-soft/texsupport.iospress-ao#1]
I am preparing a manuscript for the Applied Ontology journal and started using the new template. I encountered that the reference section is not sorted alphabetically when using the ios2-nameyear bst style file, it seems to follow the order of citation of the paper. 

This behaviour breaks with the old template and I was wondering whether this is intentional, or whether I might be missing a setting. To reproduce in the template:

```
\cite{lefever}
\cite{hankeknees}
\nocite{*} 
% if your bibliography is in bibtex format, use those commands:
\bibliographystyle{ios2-nameyear}  % Style BST file.
\bibliography{bibliography}        % Bibliography file (usually '*.bib')
```

This will result in the following order:

```
Lefever, E. (2016). A hybrid approach to domain-independent taxonomy learning. Applied Ontology, 11(3), 255–278.
Hanke, H. & Knees, D. (2017). A phase-field damage model based on evolving microstructure. Asymptotic Analysis, 101,
149–180.
Meltzer, P.S., Kallioniemi, A. & Trent, J.M. (2002). Chromosome alterations in human solid tumors. In B. Vogelstein and K.W.
Kinzler (Eds.), The Genetic Basis of Human Cancer (pp. 93–113). New York: McGraw-Hill.
Murray, P.R., Rosenthal, K.S., Kobayashi, G.S. & Pfaller, M.A. (2002). Medical Microbiology (4th ed.). St. Louis: Mosby. Wilson, E. (1991). Active vibration analysis of thin-walled beams. PhD thesis, University of Virginia.
```

**Comment by EimantasG** [comment]
@rasvaan, thank you for reporting the issue! Sorry for the late response, the notification was not received as expected. Bibliography style file ios2-nameyear.bst is fixed in the latest commit 5155c5ab8561f047c4256673efa885e4016037d4.
