### ISSUE TITLE
The class option "crcready" does not work.

### ISSUE THREAD

**Issue by alessanderbotti** [vtex-soft/texsupport.iospress-ao#2]
The class option "crcready" does not work.

**Comment by vjramirez** [comment]
I have the same issue, in the first page the line number is shown on the left only and inside the text. In the second page the visualization is correct. IOS press advice to use crcready class option to remove the page numbers. See the attached images.
![CRCReady_page1](https://user-images.githubusercontent.com/24277356/73762888-fde87280-4770-11ea-9d04-16bb56b01df4.png)
![CRCReady_page2](https://user-images.githubusercontent.com/24277356/73762926-0a6ccb00-4771-11ea-910d-5b70be7c1f95.png)

**Comment by mingiss** [comment]
The option [crcready] has been fixed.
Sorry for late response.
